# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idotenv < Formula
  desc ""
  homepage "https://github.com/h4ux/homebrew-idotenv"
  version "0.0.15"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/h4ux/idotenv/releases/download/v0.0.15/idotenv_Darwin_arm64.tar.gz"
      sha256 "b74f72c7beb851ae8a6254addd49024c038431e3b48d3efe02478d00ac1200e0"

      def install
        bin.install "idotenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/h4ux/idotenv/releases/download/v0.0.15/idotenv_Darwin_x86_64.tar.gz"
      sha256 "1067efa8682b925c131b59fea6a5a76bd28f18ce9c57284f3df5e20e575cfb26"

      def install
        bin.install "idotenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/h4ux/idotenv/releases/download/v0.0.15/idotenv_Linux_arm64.tar.gz"
      sha256 "b1974ac64a1e524b59f35e46b7c2c682952cf9c1398bfeedc6d01989a3d4c4ba"

      def install
        bin.install "idotenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/h4ux/idotenv/releases/download/v0.0.15/idotenv_Linux_x86_64.tar.gz"
      sha256 "048581f2a5a6f7a33124bf6510a0d864cb0f25cea8af3ea0fb5ec80b7a0665c4"

      def install
        bin.install "idotenv"
      end
    end
  end
end
